server:
  port: 7000
  servlet:
    context-path: /ad-sponsor # 代表controller 的前缀

spring:
  application:
    name: eureka-client-ad-sponsor
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false   # 对于一些开启懒加载的Bean 如果找不到对应的bean 就会报错 设置为false 就不会了
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ad-data?autoReconnect=true
    username: root
    password: rootpwd
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2


eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/
